#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	-- Create user if not exists
	DO \$\$
	BEGIN
		IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$TRIPPY_USER') THEN
			CREATE USER $TRIPPY_USER WITH PASSWORD '$TRIPPY_PASS';
		ELSE
			ALTER USER $TRIPPY_USER WITH PASSWORD '$TRIPPY_PASS';
		END IF;
	END
	\$\$;

	-- Create database if not exists
	SELECT 'CREATE DATABASE $TRIPPY_DB WITH OWNER $TRIPPY_USER ENCODING="UTF8" LC_COLLATE="en_US.utf8" LC_CTYPE="en_US.utf8"'
	WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$TRIPPY_DB')\gexec

	-- Grant all privileges on database
	GRANT ALL PRIVILEGES ON DATABASE $TRIPPY_DB TO $TRIPPY_USER;

	-- Connect to the database and grant schema permissions
	\c $TRIPPY_DB
	
	-- Grant all privileges on all tables in the public schema
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $TRIPPY_USER;
	GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $TRIPPY_USER;
	GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $TRIPPY_USER;
	
	-- Set default privileges for future objects
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $TRIPPY_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $TRIPPY_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $TRIPPY_USER;
EOSQL
