mode: prod # operational mode for trippy-api. E.G : "prod", "dev", "test", etc.

startup:

  # Command to run, in order, at early stage of the startup.
  # Commonly used to check, initialize or update infrastructure before start.
  execPre:
    - name: storeinit
      desc: "Check and update storage schemas"
      disabled: false
      continueOnFailure: false
      workDir:
      command: "./bin/storeinit"
      args: ["--up"]
      env:
        - STOREINIT_CONFIG=config/config.yaml

storages:
  postgresql:
    host: "127.0.0.1"
    port: 5435
    accessControl: true
    # db name, user and password must be existing ones. If they are incorrect, Trippy won't create them.
    # the below example works by default for new environments (docker or kube correctly initialized)
    trippyDB: "trippydb"
    trippyLogin: ""
    trippyPass: ""



email:
  mailjet:
    api_key_public: "" # Set via TRIPPY_EMAIL_MAILJET_API_KEY_PUBLIC env var
    api_key_private: "" # Set via MAILJET_API_KEY_PRIVATE env var
    from_name: "Trippy"
    from_email: "noreply@example.com"

httpserver:
  port: 5002
  tls: false
  jwtSecret:

base_url: "http://localhost:5002"

logging:
  level: error
  formatter: json # either 'text' or 'json'
  verbose: false # if true, log with more fields and caller

